### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bealze** [nikitavondel/steam-ts#10]
pm ERR! Linux 2.6.32-573.22.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! steam-ts@1.3.1-a start: `node lib/launch.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the steam-ts@1.3.1-a start script 'node lib/launch.js'.
npm ERR! This is most likely a problem with the steam-ts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/launch.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steam-ts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls steam-ts
npm ERR! There is likely additional logging output above.

**Comment by starwolfy** [comment]
"npm ERR! node v0.10.46
npm ERR! npm v2.15.1"

You are running a Node.js (and NPM) version from the stone age. Try updating it to at least 4.6.0 .
