### ISSUE TITLE
Error when typing !verify

### ISSUE THREAD

**Issue by NexzTV** [nikitavondel/steam-ts#11]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart steam-ts@1.3.1-a
6 info start steam-ts@1.3.1-a
7 verbose unsafe-perm in lifecycle true
8 info steam-ts@1.3.1-a Failed to exec start script
9 verbose stack Error: steam-ts@1.3.1-a start: `node lib/launch.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid steam-ts@1.3.1-a
11 verbose cwd Y:\Websites\login.dentixgaming.com
12 error Windows_NT 6.3.9600
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error steam-ts@1.3.1-a start: `node lib/launch.js`
17 error Exit status 1
18 error Failed at the steam-ts@1.3.1-a start script 'node lib/launch.js'.
18 error This is most likely a problem with the steam-ts package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node lib/launch.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs steam-ts
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls steam-ts
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by starwolfy** [comment]
I do see that you're running it on Windows which could possibly be the issue although I am not sure as I haven't really done a lot of testing on Windows. Could you copy & paste the content of npm-debug.log after it crashes?
