### ISSUE TITLE
Issue when removing a user.

### ISSUE THREAD

**Issue by JackTRG** [nikitavondel/steam-ts#12]
Hello,

I'm getting this error message upon removing a user https://i.gyazo.com/885a564bff96f1c1d3b4ec06022e945e.png - The issue only appears when there are more than 1 people linked.

Kind Regards,
Jack Hansen

**Comment by starwolfy** [comment]
Fixed, pushed 1.3.2. Thanks for the report!
https://github.com/nikitavondel/steam-ts/commit/2f8924d634ee95ec518eb30d3414e962bf1ccd92
