### ISSUE TITLE
Auto Start-up

### ISSUE THREAD

**Issue by ZeroTaps** [nikitavondel/steam-ts#13]
Hi,

New to using Linux was wondering how could I make the Steam Verify Bot start up with Linux 

did try using #! bin/bash
cd /my bot location/
./$npm start 

Any help is appreciated :)

**Comment by starwolfy** [comment]
Running the following script on startup should help you out.

```{r, engine='bash', count_lines}
#!/bin/bash
cd /botLocation
npm start
```

**Comment by ZeroTaps** [comment]
how do I add a delay to the start of this task

**Comment by ZeroTaps** [comment]
Cause the Steam Bot joins the TeamSpeak but doesn't start up the steam user maybe a delay might help I'm not sure

**Comment by starwolfy** [comment]
Beware that I have limited knowledge on bash scripting, but I believe the following should work:

```{r, engine='bash', count_lines}
#!/bin/bash
wait 15
cd /botLocation
npm start
```
This would make the script wait 15 seconds before executing the commands below it.

(I am closing this issue for now as it isn't really an issue with my application itself, but feel free to continue replying here.)
