### ISSUE TITLE
insufficient client permissions

### ISSUE THREAD

**Issue by BlackFishMaker** [nikitavondel/steam-ts#14]
So i was able to set up everything the Steam part is working fine and typing !verify also works but after i give the bot my name it says this in chat " Something went wrong, either retry !verify or contact an admin please!" and this in my console "{"id":2568,"msg":"insufficient client permissions","failed_permid":28}" it also says this every once in a while in the console "Error while querying users: [object Object]" and idea on how to fix it?

**Comment by starwolfy** [comment]
That error message should now display something useful.  https://github.com/nikitavondel/steam-ts/commit/d2b2050002357e998761ec6c4245a256216c6534

And I can tell your query client doesn't have all the permissions it needs. Try creating it via an admin account ^.

**Comment by BlackFishMaker** [comment]
how would i do that? sorry but im not that familiar with this stuff

**Comment by r3v07v3r** [comment]
Taking my issue to another thread

**Comment by starwolfy** [comment]
I suggest connecting to your teamspeak server from your root account (the one you had to fill in a token for at the beginning) and then create the query client. Or you could dive into your teamspeak permission settings and try to figure what doesn't allow you to create query clients with all the permissions.

**Comment by BlackFishMaker** [comment]
Oh now i understood it. I already tryed that, i tryed the standart server query and one that i created but both gave the same error. Maybe you can tell me what permissions it is missing exactly? Then i can ask my host to unlock them.

**Comment by starwolfy** [comment]
When you give the bot your nickname it will execute the following query commands:
- clientfind
- clientinfo
- sendtextmessage

So it'll need permission for these three.

**Comment by BlackFishMaker** [comment]
Alright the bot has all the permissions now but everytime someone trys to verify they get "User was not found on the TeamSpeak server, use !verify to restart the process." and my console is getting spammed with "Error while querying users: {"id":2568,"msg":"insufficient client permissions","failed_permid":27}" which is a different error then the one i had last time.

**Comment by starwolfy** [comment]
It's because it needs even more permissions to query the users (obtain all data about current online users), I suggest giving it all permissions since having to manually grant every permission be a bit annoying.
