### ISSUE TITLE
Something went wrong, either retry !verify or contact an admin please!

### ISSUE THREAD

**Issue by r3v07v3r** [nikitavondel/steam-ts#15]
I keep getting this message in the steam chat at the last step of verification; "bot (1.3.3): Something went wrong, either retry !verify or contact an admin please!"

I can't seem to find a log from the Bot to see whats going wrong...

I have given it Server Admin Perms

**Comment by starwolfy** [comment]
With the last step of verification you mean sending the token?

**Comment by r3v07v3r** [comment]
I send the token and get that response.

**Comment by r3v07v3r** [comment]
I send "!verify" to bot = Yes
Bot asks for my name = Yes
I send bot my name = Yes
Bot Messages me a token on Teamspeak = Yes
I send message with token to bot = Yes
Bot gives me response "Something went wrong, either retry !verify or contact an admin please!"

**Comment by starwolfy** [comment]
There is no log file the bot will output to when something goes wrong so you'd have to check the console and see what it prints when someone tries to verify themselves. Could you tell me what the console says when someone gets this message back from the bot?

**Comment by r3v07v3r** [comment]
I'll give it a try when I get home.
