### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by byRoadrunner** [nikitavondel/steam-ts#17]
Hey,
would it be possible to add these two features to the bot:
1. Send a message to the steam user if the friend request was accepted
2. Set different groups based on Ownership of different games, e.g. if the User owns ARK: Survival Evolved he would be added to the normal verify group and additionaly to an ARK group on TS (detecting of Game maybe via Steam AppID?)

**Comment by starwolfy** [comment]
Hello,

I'm afraid I am no longer implementing new features into this project anymore (I have just updated the readme of this project) as I currently don't have much time for it and my own community switched to using a different TeamSpeak verification method. Thanks for the suggestion though and perhaps we have another Nodejs programmer here who is willing to continue writing features for this project.
