### ISSUE TITLE
Request: assign TS Permission group based on Steam membership

### ISSUE THREAD

**Issue by strikerlord** [nikitavondel/steam-ts#19]
This is not an issue but more of a request.
Is it possible to have this (damn amazing and awesome) script check for specific steam member groups to determine in which permission group the user is placed?

I only tested the script today, and it works like a charm (will do a how-to video to help support this!).
Im looking for methods on how to use this script, and one of them came to mind:
Let Steam memberships help determine what sort of rights a user is going to get on Teamspeak.

Would that be possible?

**Comment by starwolfy** [comment]
This is definitely possible with the Steam API although I am no longer adding new features to this project, I'm only fixing bugs when I have the time.
