### ISSUE TITLE
Failed at the steam-ts@1.3.4 start script

### ISSUE THREAD

**Issue by strikerlord** [nikitavondel/steam-ts#26]
Since this week Steam-TS gets an error on start.

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\lib\launch.js:63:29
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:3575:11
    at replenish (D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:872:19)
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:878:27
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:840:18
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:3580:15
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:339:29
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\lib\launch.js:42:9
    at D:\Scripts\Steam TS\Steam TS\steam-ts-master\node_modules\async\dist\async.js:3575:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steam-ts@1.3.4 start: `node lib/launch.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steam-ts@1.3.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Striker\AppData\Roaming\npm-cache\_logs\2019-01-22T07_51_30_707Z-debug.log`

Ive recently moved the script from a physical Server 2012 R2 installation to a virtual one on Server 2016, it has run fine for multiple weeks.
Ive also tried restarting the installation on the 2012 R2 machine (migration isn't complete yet :) ) - and i get the exact same error there.
It seems that something has changed with Steam that causes this issue, but I can't see what for the life of me.

Any help is appreciated.
I tried updating it with the latest fixes, still the same error.

**Comment by starwolfy** [comment]
The JSON parser throws an error, most likely because your config.json file has been adjusted incorrectly. I suggest running your config file through an online validator like https://jsonlint.com/ and see what the site says about its validity.

**Comment by strikerlord** [comment]
![afbeelding](https://user-images.githubusercontent.com/15890009/51555468-ee54ff00-1e77-11e9-94d5-bb56660e84ba.png)
The config gives a "valid JSON" 

anything I can share that would help pinpointing the issue?

Threw in the launch.js on JSONLint to see what that does, and then I get this, but since its on line one, I don't think it's interesting:
![afbeelding](https://user-images.githubusercontent.com/15890009/51555855-e3e73500-1e78-11e9-9b87-ce342e6027f8.png)

**Comment by strikerlord** [comment]
Also tried running the install command again, that gave me this result, but no fix:
![afbeelding](https://user-images.githubusercontent.com/15890009/51557103-40981f00-1e7c-11e9-8846-e4536d7cf98e.png)

Ran the audit fix, didn't help.

The issue seems to have started around the 21st, there is an automatic restart mechanism that does nothing more than the start command, been using it since the first week :).
right now I created a false positive for the monitoring program so it shows "resolved" - but dont mind that.

![afbeelding](https://user-images.githubusercontent.com/15890009/51557839-4e4ea400-1e7e-11e9-99c3-66dd253d9e6a.png)

**Comment by strikerlord** [comment]
A full reinstall has been done, lost data :( but it works.

**Comment by rlnt** [comment]
Why would you lose your data due to a reinstall? Just drop the verify.json back to the data folder

**Comment by strikerlord** [comment]
> 
> 
> Why would you lose your data due to a reinstall? Just drop the verify.json back to the data folder

You sir, are a genious and a great help! It's so stupidly simple I should have thought of it, but I'm glad you pitched in!
All up and running again, with the previous verifications - thank you!

**Comment by rlnt** [comment]
No worries, could you close the issue now? :)
