### ISSUE TITLE
InvalidPassword

### ISSUE THREAD

**Issue by Forge-Media** [nikitavondel/steam-ts#3]
Failure on connection with  InvalidPassword error:

```
[ts3bot@vps ~]$ node index.js
Trying to connect to the TeamSpeak server...
Logged into the query with credentials.
Using virtual server 1 now.
Changed query client name.
{ [Error: InvalidPassword] eresult: 5 }
[ts3bot@vps ~]$
```

However as can be seen here Telnet into TS3 server with ServerQuery username and password works fine:
![](http://i.imgur.com/5L06I4v.png)

Any ideas on what is causing this?

PS: I'm an idiot, did not realize this required me to actually login to a valid steam-account. Kinda use to anonymous login. And initially thought the bot login and password, were custom commands to be used directly in TeamSpeak3.

**Please close!**

**Comment by starwolfy** [comment]
Glad to hear that you have figured it out yourself!
