### ISSUE TITLE
Config file location within node_modules causes config to be re-written?

### ISSUE THREAD

**Issue by Forge-Media** [nikitavondel/steam-ts#4]
Just want to double check whether having the config file location within node_modules will causes the config to be re-written on an update. Unless I've missed something.

As my config-file seems to be empty after I ran npm install.

Might want to consider requiring these to be paled outside of node_modules?

**Comment by Forge-Media** [comment]
Seems likely that the data/verified.json has also been re-written to a blank .json :(

**Comment by starwolfy** [comment]
What exactly did you do in order to reset the config and data files? Still do not quite understand it.

Sorry for the late reply, have been on holiday.

**Comment by starwolfy** [comment]
Going to change this project to an application instead of a module. This should not occur anymore after the next update.

**Comment by starwolfy** [comment]
Should no longer be an issue as 1.3.0
