### ISSUE TITLE
Callback already called

### ISSUE THREAD

**Issue by starwolfy** [nikitavondel/steam-ts#5]
Aware of this bug, I am currently a bit busy so it might take a few weeks to fix.

**Comment by starwolfy** [comment]
Should be fixed as of 1.3.2

**Comment by Forge-Media** [comment]
I'm assuming the following (see image) is what was fixed?

![pm2_logs_steam_ts_bot](https://cloud.githubusercontent.com/assets/7041755/18038294/11458e5a-6d8e-11e6-9061-5c617f4e8e5e.png)

Just, noticed this and wanted to double check that the error I'm seeing is the same one which 1.3.2 fixes.

Thanks

**Comment by starwolfy** [comment]
Seeing the error originates from queryusers.js I am assuming it was the callback error indeed. In order to obtain a more helpful message I recommend running the bot via 'node /lib/launch.js' as it will output the exact error to the logs, whereas here I get a more vague error message.
