### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ghost** [nikitavondel/steam-ts#6]
``` bash
npm ERR! 404 'doctormckay/steam-crypto' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'steam-user'
```

**Comment by starwolfy** [comment]
Could you write "npm -v" in your shell and tell me which version it outputs?

**Comment by ghost** [comment]
NPM version is `3.10.3`

Although I remember I did omit that somehow, is there a way to speed-up somehow the proccess of verification ? IMO, OAuth would be easier and faster, instead of steam bot, there could be a input field on website to put your TS3 nickname there, then the field to put verification code into and done.

People are lazy enough to think that steam bot is too much for such a thing.

**Comment by starwolfy** [comment]
You are correct, making use of a website and Steam's web API would make things a lot faster and simpler for the clients. However I created this project to learn more about Steam bots and to add the !verify command to an already existing steambot of mine, which has rather important functions which I cannot replicate using a webpage.
In the future, if nobody has achieved this using Steam's web API, I might create a new repository which indeed makes use of Steam's OpenID service.

**Comment by ghost** [comment]
Alright ;) you've got the point. I might try one day doing a web integrated
steam ts3 verification too :-)

2016-08-19 14:06 GMT+02:00 nikitavondel notifications@github.com:
