### ISSUE TITLE
No reply in chat.

### ISSUE THREAD

**Issue by Jo0Lz** [nikitavondel/steam-ts#7]
I've set up the bot, and it's running (I see activity in the console).
When I open up a chat with the bot and type any command (!verify) I see the command coming in on the bot (Received message from [U:1:1xxxxx]: !verify) but it doesn't send anything back...

Webpage is setup, but when I log in, no entries are there. What am I missing? :(

**Comment by starwolfy** [comment]
Couple of questions:
- What does running the command "node -v" output? If it is 4.0 or higher you're good.
- Is your Steam account limited? If yes, you might want to Google what limited accounts can and can't do.
- Is your machine possibly blocking traffic with a firewall?

**Comment by Jo0Lz** [comment]
Okay. So I just tested with my own account, which is not limited, and everything works straight away. Guess I need to add 5$ worth of euro's to the new account wallet to get it "unlimited".
Thanks!

**Comment by Jo0Lz** [comment]
On the TS forums, this line caught my eye:
"Syncing source server ranks with TeamSpeak ranks"

I already have all the CS:GO ranks on the server, is there really a way to "sync" them with the users? Can't find any documentation on it... Sorry, this probably doesn't belong here... :D

**Comment by starwolfy** [comment]
I have mentioned it as a possibility, it does not come with this project no. But if you'd happen to be/know a sourcepawn developer it could easily be done!

**Comment by Jo0Lz** [comment]
Thanks for the help! :+1:  And your time, of course.
I saw somewhere there might be plans to add some kind of web interface to allow for these actions? That would be the perfect solution.
