### ISSUE TITLE
Steam Name:

### ISSUE THREAD

**Issue by ZeroTaps** [nikitavondel/steam-ts#9]
Hi,

Love using this Node.js plugin 

just a question how do I change  the name of my bots steam name I change via steam but when I start it. it gets renamed

**Comment by starwolfy** [comment]
You'd have to navigate to the lib folder and open up 'launch.js' then replace line number 134.

From:

``` javascript
steamClient.setPersona(1, config.clanabbreviation + " bot (" + pjson.version + ")");
```

To:

``` javascript
steamClient.setPersona(1);
```
